/**
 * Compose generation — `cli-spec.md` §9.
 *
 * The compose file is DERIVED. `project.yml` is the truth (§4.2); this module
 * is a pure function from manifest + catalogue to YAML text, and every writer
 * in the CLI regenerates rather than edits. Nothing reads the compose file back
 * to learn anything — if you need a fact, it lives in the manifest.
 *
 * DETERMINISM is the property under test: same manifest, same bytes. That means
 * no timestamps, no `Object.keys` order dependence (services are sorted), and
 * no absolute paths — the bind mount is `.:/work`, relative to the file's own
 * directory, so the SSD mounting somewhere else cannot produce a diff.
 *
 * Container names come from `naming.ts`, the same module `status` matches
 * against. A rename there moves both sides at once, by construction.
 */

import { stringify as stringifyYaml } from 'yaml'
import { CprojError } from './errors.ts'
import { IMAGE_PLATFORM } from './images.ts'
import { composeProject, devContainerName, serviceContainerName } from './naming.ts'
import type { ProjectManifest } from './model/project.ts'
import type { CatalogueService, ServiceCatalogue } from './model/catalogue.ts'

export const COMPOSE_FILENAME = 'docker-compose.yml'

/** Where the project directory is mounted inside the dev container. */
export const WORKDIR = '/work'

/** The compose service key for the dev container (its container_name is `cproj-<project>`). */
export const DEV_SERVICE = 'dev'

/** Label namespace. `down-all` (Phase 4) selects on these rather than on name prefixes. */
export const LABEL_PROJECT = 'cproj.project'
export const LABEL_ROLE = 'cproj.role'
export const LABEL_SERVICE = 'cproj.service'

const HEADER = [
  '# GENERATED BY cproj — DO NOT EDIT.',
  '#',
  '# This file is derived from project.yml (cli-spec.md §4.2, §9) and is',
  '# rewritten on every `cproj new`, `cproj up`, and service add/remove.',
  '# Change project.yml instead; edits here are lost without warning.',
  '',
].join('\n')

/** `{project}` interpolation, the one substitution the catalogue promises (§4.1). */
function interpolate(template: string, project: string): string {
  return template.replaceAll('{project}', project)
}

/** Named volume for an attached service, e.g. `myapp_pgdata`. */
export function volumeName(service: CatalogueService, project: string): string {
  return interpolate(service.volume, project)
}

/** Every named volume this project owns, sorted. Used by `delete --purge`. */
export function projectVolumes(manifest: ProjectManifest, catalogue: ServiceCatalogue): string[] {
  const names: string[] = []
  for (const key of attachedKeys(manifest)) {
    const definition = catalogue.services[key]
    if (definition) names.push(volumeName(definition, manifest.name))
  }
  return names.sort()
}

/** Attached service keys in a stable (sorted) order — the determinism rule. */
export function attachedKeys(manifest: ProjectManifest): string[] {
  return Object.keys(manifest.services ?? {}).sort()
}

type ComposeService = Record<string, unknown>

function devService(manifest: ProjectManifest): ComposeService {
  // Present only when the base image is pinned (`claude-and`, whose SDK tools
  // are x86_64-only): the key is absent otherwise, so no existing project's
  // generated file gains a spurious diff.
  const platform = IMAGE_PLATFORM[manifest.base_image]

  return {
    container_name: devContainerName(manifest.name),
    image: `${manifest.base_image}:latest`,
    ...(platform ? { platform } : {}),
    // The dev container is a place to exec into, not a process to supervise.
    // `up` starts it and it waits; the agent's work happens through `exec`.
    command: ['sleep', 'infinity'],
    working_dir: WORKDIR,
    // Relative: resolved against the compose file's directory, which is the
    // project directory. Keeps the file independent of where the SSD mounts.
    volumes: [`.:${WORKDIR}`],
    // No `ports:` — the dev container publishes nothing. Services expose their
    // debugging tap; the app inside talks over the network by service name (§5).
    labels: {
      [LABEL_PROJECT]: manifest.name,
      [LABEL_ROLE]: 'dev',
    },
  }
}

function backingService(project: string, key: string, definition: CatalogueService, hostPort: number): ComposeService {
  const service: ComposeService = {
    container_name: serviceContainerName(project, key),
    image: definition.image,
    restart: 'unless-stopped',
  }

  if (definition.env && Object.keys(definition.env).length > 0) {
    const environment: Record<string, string> = {}
    for (const name of Object.keys(definition.env).sort()) {
      environment[name] = interpolate(definition.env[name] ?? '', project)
    }
    service.environment = environment
  }

  // host:container — the host side is the debugging tap (§5), the container
  // side is what the dev app connects to over the network.
  service.ports = [`${hostPort}:${definition.container_port}`]
  service.volumes = [`${volumeName(definition, project)}:${definition.mount}`]
  service.labels = {
    [LABEL_PROJECT]: project,
    [LABEL_ROLE]: 'service',
    [LABEL_SERVICE]: key,
  }
  return service
}

export type ComposeInput = {
  readonly manifest: ProjectManifest
  /** Needed only when the manifest attaches services; pass null for a bare project. */
  readonly catalogue: ServiceCatalogue | null
}

/**
 * Build the compose document. Throws SERVICE_UNKNOWN when the manifest names a
 * service the catalogue does not define — the alternative is generating a
 * compose file that silently omits a service the user believes is attached.
 */
export function composeDocument({ manifest, catalogue }: ComposeInput): Record<string, unknown> {
  const project = manifest.name
  const services: Record<string, ComposeService> = { [DEV_SERVICE]: devService(manifest) }
  const volumes: Record<string, unknown> = {}

  for (const key of attachedKeys(manifest)) {
    const definition = catalogue?.services[key]
    if (!definition) {
      throw new CprojError(
        'SERVICE_UNKNOWN',
        `Project \`${project}\` attaches service \`${key}\`, which the service catalogue does not define.`,
      )
    }
    const attachment = manifest.services?.[key]
    if (!attachment) continue
    services[key] = backingService(project, key, definition, attachment.host_port)

    const volume = volumeName(definition, project)
    volumes[volume] = {
      name: volume,
      // Labelled so Phase 4 can attribute an orphaned volume to the project it
      // came from without keeping a second registry.
      labels: { [LABEL_PROJECT]: project, [LABEL_SERVICE]: key },
    }
  }

  const document: Record<string, unknown> = {
    // Compose's own project name. Also the default network's name, so two
    // projects' containers cannot see each other.
    name: composeProject(project),
    services,
  }
  if (Object.keys(volumes).length > 0) document.volumes = volumes
  return document
}

/** The generated file's text, header comment included. Deterministic. */
export function renderCompose(input: ComposeInput): string {
  const yaml = stringifyYaml(composeDocument(input), {
    // Fixed formatting options: a default that changes with the `yaml` version
    // would show up as a spurious diff in every project at once.
    indent: 2,
    lineWidth: 0,
    singleQuote: false,
  })
  return `${HEADER}${yaml}`
}
