/**
 * Compose generation — `cli-spec.md` §9.
 *
 * The compose file is DERIVED. `project.yml` is the truth (§4.2); this module
 * is a pure function from manifest + catalogue to YAML text, and every writer
 * in the CLI regenerates rather than edits. Nothing reads the compose file back
 * to learn anything — if you need a fact, it lives in the manifest.
 *
 * DETERMINISM is the property under test: same manifest, same bytes. That means
 * no timestamps, no `Object.keys` order dependence (services are sorted), and
 * no absolute paths — every bind is relative to the file's own directory
 * (`./work:/work`, `./data/postgres:…`), so the root mounting somewhere else
 * cannot produce a diff.
 *
 * Container names come from `naming.ts`, the same module `status` matches
 * against. A rename there moves both sides at once, by construction.
 */

import { stringify as stringifyYaml } from 'yaml'
import { BardolierError } from './errors.ts'
import { CONTAINER_HOME, IMAGE_CACHE, IMAGE_PLATFORM } from './images.ts'
import { CONTAINER_DATA, CONTAINER_LOCAL, CONTAINER_WORK, DATA_DIR, HOME_DIR, LOCAL_DIR, WORK_DIR } from './layout.ts'
import { ARCHETYPE_APP_PORT } from './model/archetype.ts'
import { extraPortNames } from './extraports.ts'
import { selectedImage } from './deps.ts'
import { composeProject, devContainerName, serviceContainerName } from './naming.ts'
import type { ProjectManifest } from './model/project.ts'
import type { CatalogueService, ServiceCatalogue } from './model/catalogue.ts'
import type { ImageCache } from './images.ts'

export const COMPOSE_FILENAME = 'docker-compose.yml'

/** The compose service key for the dev container (its container_name is `bardolier-<project>`). */
export const DEV_SERVICE = 'dev'

/** Label namespace. `down-all` (Phase 4) selects on these rather than on name prefixes. */
export const LABEL_PROJECT = 'bardolier.project'
export const LABEL_ROLE = 'bardolier.role'
export const LABEL_SERVICE = 'bardolier.service'

/** `bardolier.role` on the shared toolchain cache volume — it belongs to no project. */
export const ROLE_CACHE = 'cache'

/**
 * Host environment the dev container inherits, if the host has it — `cli-spec.md`
 * §9.
 *
 * Written in Compose's LIST form (a bare `NAME`, no `=`), which is the only
 * shape with the semantics this needs: pass the value through when the
 * environment running `compose up` has one, and leave the variable UNSET in the
 * container when it does not. The map form would have to write `${NAME:-}`, and
 * an empty-string token is not the same as no token — it is a credential that
 * fails instead of a login prompt.
 *
 * That it is a fixed, sorted list is what keeps the generated file deterministic
 * (§9): the same manifest renders the same bytes on a machine that has none of
 * these set and on one that has all of them. What varies is the container's
 * environment, which is not the file's business.
 *
 * `GIT_*` are git's own documented identity variables, so a commit made in here
 * is attributed to the human rather than failing on an unset `user.email`; `up`
 * fills them from the host's own `git config`. The tokens are passed rather than
 * stored: a credential in `~/.config/bardolier/config.yml` would be a plaintext
 * secret this tool had chosen to keep, and it never needs to keep one — the
 * persistent home (`CONTAINER_HOME`) is where a `claude login` or an ssh key
 * lives across a `down`.
 */
export const PASSTHROUGH_ENV: readonly string[] = [
  'ANTHROPIC_API_KEY',
  'CLAUDE_CODE_OAUTH_TOKEN',
  'GH_TOKEN',
  'GITHUB_TOKEN',
  'GIT_AUTHOR_EMAIL',
  'GIT_AUTHOR_NAME',
  'GIT_COMMITTER_EMAIL',
  'GIT_COMMITTER_NAME',
]

/** The labels `up` creates a cache volume with, so the scan can recognise ours. */
export const CACHE_VOLUME_LABELS: Readonly<Record<string, string>> = { [LABEL_ROLE]: ROLE_CACHE }

/** The shared dependency cache this project's base image needs, if any (`images.ts`). */
export function cacheFor(manifest: ProjectManifest): ImageCache | null {
  return IMAGE_CACHE[manifest.base_image] ?? null
}

const HEADER = [
  '# GENERATED BY bardolier — DO NOT EDIT.',
  '#',
  '# This file is derived from project.yml (cli-spec.md §4.2, §9) and is',
  '# rewritten on every `bardolier new`, `bardolier up`, and service add/remove.',
  '# Change project.yml instead; edits here are lost without warning.',
  '',
].join('\n')

/** `{project}` interpolation, the one substitution the catalogue promises (§4.1). */
function interpolate(template: string, project: string): string {
  return template.replaceAll('{project}', project)
}

/** Attached service keys in a stable (sorted) order — the determinism rule. */
export function attachedKeys(manifest: ProjectManifest): string[] {
  return Object.keys(manifest.services ?? {}).sort()
}

type ComposeService = Record<string, unknown>

/**
 * The dev server's `host:container` publication, or null — `cli-spec.md` §9.
 *
 * Both halves must be present: an archetype that serves something
 * (`ARCHETYPE_APP_PORT`) and a manifest that has actually been assigned a host
 * port. A project created before the field existed has the first and not the
 * second, and publishes nothing until its next `up` assigns one — which is what
 * keeps its generated file from changing under it in the meantime.
 */
function appPublication(manifest: ProjectManifest): { host: number; container: number } | null {
  const container = ARCHETYPE_APP_PORT[manifest.archetype]
  const host = manifest.app_port
  if (container === undefined || typeof host !== 'number') return null
  return { host, container }
}

/**
 * Extra ports' `host:container` publications, sorted by name (the determinism
 * rule) — `cli-spec.md` §5.1, §9. Archetype-independent: unlike
 * `appPublication`, nothing here asks what the archetype serves, because these
 * are declared by the caller (`port add`) rather than fixed by the image.
 */
function extraPublications(manifest: ProjectManifest): string[] {
  return extraPortNames(manifest).map((name) => {
    const attachment = manifest.extra_ports?.[name]
    return `${attachment?.host_port}:${attachment?.container_port}`
  })
}

function devService(manifest: ProjectManifest): ComposeService {
  // Present only when the base image is pinned (`bardolier-and`, whose SDK tools
  // are x86_64-only): the key is absent otherwise, so no existing project's
  // generated file gains a spurious diff.
  const platform = IMAGE_PLATFORM[manifest.base_image]
  // Shared across every project on this image, so it is NOT a project volume:
  // `up` creates it and Compose only mounts it (`external: true` below).
  const cache = cacheFor(manifest)
  const app = appPublication(manifest)
  const extra = extraPublications(manifest)
  const ports = [...(app ? [`${app.host}:${app.container}`] : []), ...extra]

  return {
    container_name: devContainerName(manifest.name),
    // The plain base image, or a derived one built at `up` when the project
    // declares extra OS packages (§9's image-selection rule; `deps.ts`).
    image: selectedImage(manifest),
    ...(platform ? { platform } : {}),
    // The dev container is a place to exec into, not a process to supervise.
    // `up` starts it and it waits; the agent's work happens through `exec`.
    command: ['sleep', 'infinity'],
    working_dir: CONTAINER_WORK,
    // `PORT` first, because it carries a value and the rest do not: it tells the
    // dev server which port to bind, so every project's server config is the
    // same fixed number however its host port was allocated. Then what the host
    // lends the container, if it has it (PASSTHROUGH_ENV).
    environment: [...(app ? [`PORT=${app.container}`] : []), ...PASSTHROUGH_ENV],
    // Four relative binds, resolved against the compose file's own directory,
    // so the file stays independent of where the root mounts (§4.2, phase 19).
    // `/data` is READ-ONLY here: the data is visible for inspection, but
    // writing into a live data directory from a second container corrupts it —
    // the service that owns it mounts the same path read-write below. Last is
    // the toolchain cache, the one named volume left, shared by every project
    // on this base image (`images.ts`).
    volumes: [
      `./${WORK_DIR}:${CONTAINER_WORK}`,
      `./${DATA_DIR}:${CONTAINER_DATA}:ro`,
      `./${LOCAL_DIR}:${CONTAINER_LOCAL}`,
      `./${HOME_DIR}:${CONTAINER_HOME}`,
      ...(cache ? [`${cache.volume}:${cache.mount}`] : []),
    ],
    // §9's exceptions to "the dev container publishes nothing": the
    // archetype's dev server, which a browser on the Mac has to reach and
    // cannot reach over the Docker network, plus any extra ports the caller
    // declared (§5.1) for the same reason — a mobile client, a second
    // frontend, an interactive dev tool. Services are still the other way
    // round — their host port is a debugging tap and the app inside talks to
    // them by service name (§5).
    ...(ports.length > 0 ? { ports } : {}),
    labels: {
      [LABEL_PROJECT]: manifest.name,
      [LABEL_ROLE]: 'dev',
    },
  }
}

function backingService(project: string, key: string, definition: CatalogueService, hostPort: number): ComposeService {
  const service: ComposeService = {
    container_name: serviceContainerName(project, key),
    image: definition.image,
    restart: 'unless-stopped',
  }

  if (definition.env && Object.keys(definition.env).length > 0) {
    const environment: Record<string, string> = {}
    for (const name of Object.keys(definition.env).sort()) {
      environment[name] = interpolate(definition.env[name] ?? '', project)
    }
    service.environment = environment
  }

  // host:container — the host side is the debugging tap (§5), the container
  // side is what the dev app connects to over the network.
  service.ports = [`${hostPort}:${definition.container_port}`]
  // The service's own data directory inside the project, named by its
  // catalogue key — same disk as the project, outside any working tree.
  service.volumes = [`./${DATA_DIR}/${key}:${definition.mount}`]
  service.labels = {
    [LABEL_PROJECT]: project,
    [LABEL_ROLE]: 'service',
    [LABEL_SERVICE]: key,
  }
  return service
}

export type ComposeInput = {
  readonly manifest: ProjectManifest
  /** Needed only when the manifest attaches services; pass null for a bare project. */
  readonly catalogue: ServiceCatalogue | null
}

/**
 * Build the compose document. Throws SERVICE_UNKNOWN when the manifest names a
 * service the catalogue does not define — the alternative is generating a
 * compose file that silently omits a service the user believes is attached.
 */
export function composeDocument({ manifest, catalogue }: ComposeInput): Record<string, unknown> {
  const project = manifest.name
  const services: Record<string, ComposeService> = { [DEV_SERVICE]: devService(manifest) }
  const volumes: Record<string, unknown> = {}

  for (const key of attachedKeys(manifest)) {
    const definition = catalogue?.services[key]
    if (!definition) {
      throw new BardolierError(
        'SERVICE_UNKNOWN',
        `Project \`${project}\` attaches service \`${key}\`, which the service catalogue does not define.`,
      )
    }
    const attachment = manifest.services?.[key]
    if (!attachment) continue
    services[key] = backingService(project, key, definition, attachment.host_port)
  }

  // The only named volume a project's compose file still declares, and
  // deliberately not project-labelled: the toolchain cache is shared
  // by every project on this base image, so Compose must neither create it nor
  // claim it — `external: true` means "mount what `up` already made". Without
  // that, the first android project's Compose stamps its own project label on
  // the volume and every other one warns about it on every `up`.
  const cache = cacheFor(manifest)
  if (cache) volumes[cache.volume] = { name: cache.volume, external: true }

  const document: Record<string, unknown> = {
    // Compose's own project name. Also the default network's name, so two
    // projects' containers cannot see each other.
    name: composeProject(project),
    services,
  }
  if (Object.keys(volumes).length > 0) document.volumes = volumes
  return document
}

/** The generated file's text, header comment included. Deterministic. */
export function renderCompose(input: ComposeInput): string {
  const yaml = stringifyYaml(composeDocument(input), {
    // Fixed formatting options: a default that changes with the `yaml` version
    // would show up as a spurious diff in every project at once.
    indent: 2,
    lineWidth: 0,
    singleQuote: false,
  })
  return `${HEADER}${yaml}`
}
